/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.semgus.unrealizability;

import org.semgus.java.problem.ProblemGenerator;
import org.semgus.java.problem.SemgusProblem;

import java.io.FileReader;
import java.io.Reader;

public class App {
    public static void main(String[] args) {
        SemgusProblem problem;
        try (Reader reader = new FileReader(args[1])) {
            problem = ProblemGenerator.parse(reader);
        } catch (Exception ex) {
            ex.printStackTrace();
            return;
        }

        System.out.println(problem.dump());
    }
}
